### ISSUE TITLE
Question about the install script (SweetSecurity.sh)

### ISSUE THREAD

**Issue by sabx** [TravisFSmith/SweetSecurity#10]
In line #74 we do:
sudo cp SweetSecurity/logstash.conf /etc/logstash/conf.d

However, later in #105 we do:
sudo sed -i -- "s/SMTP_HOST/"$smtpHost"/g" /opt/logstash/logstash.conf

but the logstash.conf file was copied into the /etc/logstash/conf.d directory and not the /opt/logstash directory.

**Comment by webhead404** [comment]
I will wait for TravisFSmith to respond but I changed 

sudo sed -i -- "s/SMTP_HOST/"$smtpHost"/g" /opt/logstash/logstash.conf

to 
sudo sed -i -- "s/SMTP_HOST/"$smtpHost"/g" /etc/logstash/conf.d/logstash.conf

and I finally have data. Good catch!
