### ISSUE TITLE
sqlite3 create db script needs column for omp_id

### ISSUE THREAD

**Issue by n00btotal** [TravisFSmith/SweetSecurity#11]
Currently this gives you an error:

networkDiscovery.py (line 138)

`c.execute("INSERT INTO hosts VALUES ('" + hostname + "'," + str(ip2long(ipaddress)) + ",'" + macaddress + "','" + macvendor + "','" + omp_id + "')")`

Unless you ad a fifth text column for omp_id in your SweetSecurity.db.

I suggest the following 
`c.execute('''CREATE TABLE hosts(hostname text, ip4 integer, mac text, vendor text, ompid text)''')`

to replace line 10 in SweetSecurityDB.py
`c.execute('''CREATE TABLE hosts(hostname text, ip4 integer, mac text, vendor text)''')`

**Comment by TravisFSmith** [comment]
OpenVas is no longer installed along with Sweet Security.
