### ISSUE TITLE
GeoIP

### ISSUE THREAD

**Issue by shyheim1** [TravisFSmith/SweetSecurity#12]
How do I get geoip working in logstash and kibana? Can you upload a config file with geoip?

**Comment by TravisFSmith** [comment]
See the logstash config file on how to get Geo IP working.  Note that this uses two geoip fields, so you will need to update the logsatsh template in elasticsearch accordingly.  

Logsatsh Config:
https://github.com/TravisFSmith/SweetSecurity/blob/2.0/logstash/conf/logstash.conf

Template Command:
https://github.com/TravisFSmith/SweetSecurity/blob/2.0/install/logstash.py#L136
