### ISSUE TITLE
Bro IDS Status issue on SweetSecurity settings webpage

### ISSUE THREAD

**Issue by buckshome** [TravisFSmith/SweetSecurity#16]
The Bro IDS status on the SweetSecurity Settings web page always says "crashed" even though it is running on the remote Debian9 VM    I've tried restarting pretty much everything and nothing seems to change it.   Anyone running into this?   

![image](https://user-images.githubusercontent.com/30200081/28253878-0b43b802-6a76-11e7-89a9-716cafe8fbb1.png)

![image](https://user-images.githubusercontent.com/30200081/28253943-6cdd7db4-6a76-11e7-8fc1-f717666869fd.png)

**Comment by TravisFSmith** [comment]
The webapp wasn't updating the server with the info being sent by the client.  Fix outlined here: 

https://github.com/TravisFSmith/SweetSecurity/commit/0902fc36d1e3cdf0437ece6a22dcedb6f47b9eec

You can manually replace that specific line in your __init__.py file.
