### ISSUE TITLE
setup.py on clean system complaining about lack of memory

### ISSUE THREAD

**Issue by toqduj** [TravisFSmith/SweetSecurity#17]
Dear Travis, 

I'm trying to install the "sensor"-batch of programs of your sweet suite. However, even on a clean raspbian system, when running the setup.py script, I get the complaint that I have less than 1 GB of memory, and that I need more than that to continue. 

Available space on the root partition is 24G. RAM's not something I can change. Curious to know how this should be installed.

**Comment by TravisFSmith** [comment]
If you have less than 900 mb of RAM it will throw this error.

Can you post the output of 'free -t -m'?  

Which hardware version of the Raspberry Pi are you running on?

This is a soft error, so you can bypass it and still install if you like.  To manually do so, comment out lines 82 through 86 of setup.py.

**Comment by toqduj** [comment]
It's a Rpi 3B
Ah, I forgot that I reserved 196 MB for GPU memory. Setting that back to 64 resolved the issue. Sorry for the oversight!
