### ISSUE TITLE
Kibana not running

### ISSUE THREAD

**Issue by guy38370** [TravisFSmith/SweetSecurity#3]
Hello, I've install without any error Sweetsecurity which i found very interresting
Before and after reboot kibana isn't running
When i start it manually in /opt.. , i get following message which continue unitil i kill it
Seems localhost port 9200 isn't open
Below processes list
(Running on a pi2 Under Jessy)

What did i miss and how to correct the Problem ?

Thanks for Your help
## Guy (from France)

{"name":"Kibana","hostname":"raspi-tripwire","pid":805,"level":50,"err":"Request error, retrying -- connect ECONNREFUSED 127.0.0.1:9200","msg":"","time":"2016-04-03T11:54:41.394Z","v":0}
## {"name":"Kibana","hostname":"raspi-tripwire","pid":805,"level":40,"msg":"Unable to revive connection: http://localhost:9200/","time":"2016-04-03T11:54:41.456Z","v":0}

UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 11:49 ?        00:00:04 /sbin/init
root         2     0  0 11:49 ?        00:00:00 [kthreadd]
root         3     2  0 11:49 ?        00:00:00 [ksoftirqd/0]
root         5     2  0 11:49 ?        00:00:00 [kworker/0:0H]
root         6     2  0 11:49 ?        00:00:00 [kworker/u8:0]
root         7     2  0 11:49 ?        00:00:00 [rcu_sched]
root         8     2  0 11:49 ?        00:00:00 [rcu_bh]
root         9     2  0 11:49 ?        00:00:00 [migration/0]
root        10     2  0 11:49 ?        00:00:00 [migration/1]
root        11     2  0 11:49 ?        00:00:00 [ksoftirqd/1]
root        13     2  0 11:49 ?        00:00:00 [kworker/1:0H]
root        14     2  0 11:49 ?        00:00:00 [migration/2]
root        15     2  0 11:49 ?        00:00:00 [ksoftirqd/2]
root        17     2  0 11:49 ?        00:00:00 [kworker/2:0H]
root        18     2  0 11:49 ?        00:00:00 [migration/3]
root        19     2  0 11:49 ?        00:00:00 [ksoftirqd/3]
root        20     2  0 11:49 ?        00:00:00 [kworker/3:0]
root        21     2  0 11:49 ?        00:00:00 [kworker/3:0H]
root        22     2  0 11:49 ?        00:00:00 [khelper]
root        23     2  0 11:49 ?        00:00:00 [kdevtmpfs]
root        24     2  0 11:49 ?        00:00:00 [netns]
root        25     2  0 11:49 ?        00:00:00 [perf]
root        26     2  0 11:49 ?        00:00:00 [khungtaskd]
root        27     2  0 11:49 ?        00:00:00 [writeback]
root        28     2  0 11:49 ?        00:00:00 [crypto]
root        29     2  0 11:49 ?        00:00:00 [bioset]
root        30     2  0 11:49 ?        00:00:00 [kblockd]
root        31     2  0 11:49 ?        00:00:00 [kworker/1:1]
root        32     2  0 11:49 ?        00:00:00 [rpciod]
root        33     2  0 11:49 ?        00:00:00 [kswapd0]
root        34     2  0 11:49 ?        00:00:00 [fsnotify_mark]
root        35     2  0 11:49 ?        00:00:00 [nfsiod]
root        41     2  0 11:49 ?        00:00:00 [kthrotld]
root        43     2  0 11:49 ?        00:00:00 [VCHIQ-0]
root        44     2  0 11:49 ?        00:00:00 [VCHIQr-0]
root        45     2  0 11:49 ?        00:00:00 [VCHIQs-0]
root        46     2  0 11:49 ?        00:00:00 [iscsi_eh]
root        47     2  0 11:49 ?        00:00:00 [dwc_otg]
root        48     2  0 11:49 ?        00:00:00 [DWC Notificatio]
root        49     2  0 11:49 ?        00:00:00 [kworker/u8:1]
root        50     2  0 11:49 ?        00:00:00 [kworker/2:1]
root        51     2  0 11:49 ?        00:00:01 [mmcqd/0]
root        52     2  0 11:49 ?        00:00:00 [VCHIQka-0]
root        53     2  0 11:49 ?        00:00:00 [SMIO]
root        54     2  0 11:49 ?        00:00:00 [deferwq]
root        55     2  0 11:49 ?        00:00:00 [kworker/1:2]
root        56     2  0 11:49 ?        00:00:00 [jbd2/mmcblk0p2-]
root        57     2  0 11:49 ?        00:00:00 [ext4-rsv-conver]
root        59     2  0 11:49 ?        00:00:00 [ipv6_addrconf]
root        96     2  0 11:49 ?        00:00:00 [kworker/2:2]
root       104     1  0 11:49 ?        00:00:00 /lib/systemd/systemd-journald
root       107     1  0 11:49 ?        00:00:00 /lib/systemd/systemd-udevd
root       230     2  0 11:49 ?        00:00:00 [kworker/3:2]
root       346     1  0 11:49 ?        00:00:00 /usr/sbin/cron -f
root       349     1  0 11:49 ?        00:00:00 /lib/systemd/systemd-logind
avahi      353     1  0 11:49 ?        00:00:00 avahi-daemon: running [raspi-tripwire.local]
message+   355     1  0 11:49 ?        00:00:00 /usr/bin/dbus-daemon --system --address=systemd: --n
nobody     371     1  0 11:49 ?        00:00:00 /usr/sbin/thd --daemon --triggers /etc/triggerhappy/
root       376     2  0 11:49 ?        00:00:00 [cfg80211]
root       380     1  0 11:49 ?        00:00:00 /sbin/dhcpcd -q -b
avahi      386   353  0 11:49 ?        00:00:00 avahi-daemon: chroot helper
logstash   402     1 17 11:49 ?        00:02:17 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweep
root       439     2  0 11:49 ?        00:00:00 [kworker/2:1H]
root       440     2  0 11:49 ?        00:00:00 [kworker/1:1H]
root       441     2  0 11:49 ?        00:00:00 [kworker/3:1H]
root       444     1  0 11:49 ?        00:00:00 /usr/sbin/rsyslogd -n
root       475     1  0 11:49 ?        00:00:00 /usr/sbin/sshd -D
root       513     2  0 11:49 ?        00:00:00 [kworker/0:2]
root       520     1  0 11:49 tty1     00:00:00 /bin/login -f
root       522     1  0 11:49 ?        00:00:00 /sbin/agetty --keep-baud 115200 38400 9600 ttyAMA0 v
ntp        525     1  0 11:49 ?        00:00:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 106:111
pi         561     1  0 11:49 ?        00:00:00 /lib/systemd/systemd --user
pi         568   561  0 11:49 ?        00:00:00 (sd-pam)
pi         576   520  0 11:49 tty1     00:00:00 -bash
root       751   475  0 11:51 ?        00:00:00 sshd: pi [priv]
pi         761   751  0 11:51 ?        00:00:00 sshd: pi@pts/0
pi         764   761  0 11:51 pts/0    00:00:00 -bash
root       804     2  0 11:54 ?        00:00:00 [kworker/0:0]
root       826     2  0 11:58 ?        00:00:00 [kworker/3:1]
root       830     2  0 12:00 ?        00:00:00 [kworker/0:1]
pi         837   764  0 12:02 pts/0    00:00:00 ps -ef

**Comment by TravisFSmith** [comment]
Port 9200 is elasticsearch, which does not seem to be started.
