### ISSUE TITLE
critical-stack and lack of memory on my raspberry pi 3

### ISSUE THREAD

**Issue by ysimonx** [TravisFSmith/SweetSecurity#4]
Hello

what a wonderfull idea SweetSecurity

however ...
- when installing critical-stack, with many feeds, when building master file.dat ... i have a memory issue, the master.xxx.dat file can not be built ...
- i have to choose only a few feeds ... but, then, this is the "bro" process taking >90% CPU and >80% memory
- also, i had to add "@load /opt/critical-stack/frameworks/intel/" to /opt/nsm/bro/share/bro/site/local.bro 

i wish you the best :)

**Comment by ysimonx** [comment]
i run raspbian with noobs
the space available on the sd card is very small, and because of noobs, it's nearly impossible to expand the partition to the full sdcard

my swap file is only 100 Mb

**Comment by TravisFSmith** [comment]
Can you provide either

- List of feeds from Critical Stack
- Number of feeds/IOC's from Critical Stack
