### ISSUE TITLE
filecheck.io

### ISSUE THREAD

**Issue by meiguoren** [TravisFSmith/SweetSecurity#43]
Is this site still a thing? I went ahead and clicked yes to connect to https://filechck.io and it never comes up. I feel like I'm doing something wrong.

**Comment by rndrev** [comment]
I'll answer your question and maybe someone will answer mine.

You can see in the code the URL that he uses:
https://github.com/TravisFSmith/SweetSecurity/search?q=filecheck.io&unscoped_q=filecheck.io

I believe that you are right and this site is no more.

**Comment by meiguoren** [comment]
Ok, thanks for the help.
